### PR TITLE
e2e: RPS: fix expected cpu set

### PR DESCRIPTION
**Pull request by ffromani**
Because of a logic oversight, the expected cpu set was overwritten with the value expected for physical devices after the first loop iteration. This broke the test when running on clusters with more than a single worker node.

### CODE REVIEW

**Comment by zeeke** [comment]
LGTM

**Comment by Tal-or** [comment]
/lgtm
Good catch!

**Comment by ffromani** [comment]
/override ci/prow/e2e-hypershift

none of the failures are obviously related to this lane, which seems to be failing also with other (still unrelated) PRs

**Pull request merged**
