### PR TITLE
Jira PSAP-1288: NTO operand cleanup

### PR DESCRIPTION
**Pull request by jmencak**
In preparation for running `TuneD` prior to kubelet, make things simpler and cleaner.

Notable changes:
  * Even though there is currently no namespace collision with `TuneD` using in /var/lib/tuned, change this path to /var/lib/ocp-tuned
  * Remove bin/run.  While this means a little code duplication across Containerfiles, we no longer need to do anything special at run time.  This should make things easier for the future.
  * Do not inherit `--enable-leader-election` and `--version` NTO flags as they are not handled by subcommands anyway (yet)
  * Remove openshift-tuned binary and use NTO subcommand instead.
  * /var/lib/tuned/profiles-data is no longer used, remove it.
  * Remove openshift-tuned PID file code.  It is no longer used.
  * Clean up after PR844

### CODE REVIEW

**Comment by jmencak** [comment]
> Until when do we need to maintain [Dockerfile.rhel8](https://github.com/openshift/cluster-node-tuning-operator/pull/970/files#diff-9da637863f1a7b402a22724a788049d8571eed68b5c023ad2a1314008791caed) ?

As long as 4.12 is supported, because it is the last one, where NTO uses RHEL8 as the base.  I'd say we can safely drop it after January 17, 2025.

**Review by MarSik — APPROVED** [review]
This looks good to me. I will let Yanir issue the last lgtm as he had a question.

**Comment by yanirq** [comment]
> This looks good to me. I will let Yanir issue the last lgtm as he had a question.

lgtm as well (although the bot already has interpreted the comment as lgtm)

**Comment by MarSik** [comment]
Heh, I thought you have to use the command form of lgtm. The bot is too smart it seems :)

**Pull request merged**
