### PR TITLE
OCPBUGS-17941: Tighten the rules for modifying Tuned Profiles

### PR DESCRIPTION
**Pull request by jmencak**
NTO operands allow updating Tuned Profiles.  This is intentional and by design
as some host information needs to be communicated back to the NTO operator,
but this also allows a successful local attacker potentially affect node-level
configuration of other cluster nodes.

This change addresses the situation in two ways.  First, scoped RBAC
permissions on Profile.status subresource is used to disallow Node-level
write access to Profile.spec.  Second, the Node resource is used to provide
status loops back to NTO using the kubelet credential to write an annotation
to the Node resource.

This change also simplifies the mechanism for accepting kernel
command-line parameters as calculated by the NTO operands.  Now, all NTO
operands must agree on the calculated kernel command-line parameters.

ClusterOperator/node-tuning now also reports operand version.  The
operand version changes only when all operand replicas have successfully
upgraded and are ready.  This information is used to block PPC
Reconcilation loop until the operator and operand RELEASE_VERSION agree.
This is a short-term measure to prevent from multiple node reboots
during upgrades.

Other fixes:
  - Disallow MC updates during upgrades when kernel command-line
    parameters of nodes within a MCP do not match.
  - ClusterOperator/node-tuning object was sometimes giving false
    information based on an old Metadata.Generation.

Resolves: OCPBUGS-17941

This is a backport of https://github.com/openshift/cluster-node-tuning-operator/pull/775

### CODE REVIEW

**Comment by jmencak** [comment]
/cc @dagrayvid 
This is a straightforward port of https://github.com/openshift/cluster-node-tuning-operator/pull/765 to 4.13.  Would you be able to take a look when available?  Thank you!

**Comment by jmencak** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade 10

**Comment by jmencak** [comment]
@dagrayvid , when you have a minute, would you be able to review this backport of: https://github.com/openshift/cluster-node-tuning-operator/pull/775 ? Thank you.

**Comment by dagrayvid** [comment]
Sorry for the delay!

/lgtm

**Comment by jmencak** [comment]
Thank you David.
/label backport-risk-assessed
@mrniranjan in Liquan's absence, would you be able to provide cherry-pick-approved label, please?

**Pull request merged**
