### PR TITLE
PSAP-1567: Bump the latest k8s and OpenShift dependencies

### PR DESCRIPTION
**Pull request by jmencak**
Notable changes:
  * Removed most pinned dependencies.
  * Updated PPC code to work with the latest sigs.k8s.io/controller-runtime v0.19.0 as its low-level API changed.
  * Updated main.go to use new caching options.
  * Switched from "github.com/openshift/kubernetes-sigs-controller-tools" controller-gen to "sigs.k8s.io/controller-tools/cmd/controller-gen".  Even the latest upstream openshift's controller-gen (and all others including v0.9.2) were failing during CRD generation with: unable to locate schema for type "k8s.io/api/core/v1".ConditionStatus. That issue was fixed in "github.com/openshift/kubernetes-sigs-controller-tools", see https://github.com/kubernetes-sigs/controller-tools/issues/324
  * Fixed performanceprofile_types.go for v1alpha1 to generate API deepcopy objects.

### CODE REVIEW

**Comment by ffromani** [comment]
/lgtm

with such a large change, we can only trust CI

**Comment by jmencak** [comment]
Grrr, forgot to run the linter. :/

**Comment by jmencak** [comment]
Hmm, it looks like the linter is optional.  We should really change this.  [Follow-up PR to fix the linter](https://github.com/openshift/cluster-node-tuning-operator/pull/1196).

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-fips-payload-scan

**Pull request merged**
