### PR TITLE
Switch to golang 1.19

### PR DESCRIPTION
**Pull request by jmencak**
This change switches to golang 1.19 and addresses formatting issues in the code fixed by the switch to golang 1.19.

### CODE REVIEW

**Review by fromanirh — COMMENTED** [review]
/lgtm

**Comment by jmencak** [comment]
```
Couldn't resolve host name for https://ocp-artifacts.hosts.prod.psi.rdu2.redhat.com/pub/RHOCP/plashets/4.9/stream/el8/latest/x86_64/os/repodata/repomd.xml [Could not resolve host: ocp-artifacts.hosts.prod.psi.rdu2.redhat.com]
```
Network errors?
/retest

**Comment by jmencak** [comment]
Looking better than last time, but `ci/prow/e2e-gcp-pao` is still failing.
/retest

**Comment by jmencak** [comment]
Let's see if today the `ci/prow/e2e-gcp-pao` has a better day...
/retest

**Pull request merged**
