### PR TITLE
e2e: remove image parameter from PAO must gather

### PR DESCRIPTION
**Pull request by SargunNarula**
The PAO must gather is being merged with the NTO and hence in the updated versions the image parameter is not required to be given with the oc adm command.

Adapt this change in tests and remove the image parameter from the different places.

### CODE REVIEW

**Comment by shajmakh** [comment]
Thanks for the PR! for now it looks good and that we need this change.
as synced offline, let's wait for the OCP build to be available for testing the changes.
/hold

**Comment by shajmakh** [comment]
A build is available and was tested by @SargunNarula 
/hold cancel

**Comment by shajmakh** [comment]
@SargunNarula let's remove the draft and propose the PR for reviewers.
lgtm from my end.

**Review by MarSik — APPROVED** [review]
/lgtm

**Comment by shajmakh** [comment]
The CI failures are due to the new modifications done with respect to cgroupv2 work.

**Comment by ffromani** [comment]
We don't usually accept PRs with merge commits. Please rebase your change instead of using `git merge`.

**Pull request closed without merging**
