### PR TITLE
OCPBUGS-33112: E2E: Add automation to check default cpuset from cpu manager state file

### PR DESCRIPTION
**Pull request by mrniranjan**
Add new automation to verify default cpuset from the cpu manager state file pre and post kubelet restart Automates https://issues.redhat.com/browse/OCPBUGS-24366

### CODE REVIEW

**Comment by ffromani** [comment]
looks reasonnable and automates the bug per subject, but anything which consumes the state files directly is tech debt and we need to treat is as such.

**Comment by mrniranjan** [comment]
@ffromani i have modified the test case to check with a gu pod which was the original issue.

**Comment by ffromani** [comment]
> @ffromani i have modified the test case to check with a gu pod which was the original issue.

thanks, but the main issue remains. I guess we don't have better approaches handy, though. We need to start doing these checks using supported APIs, like the podresources API

**Comment by mrniranjan** [comment]
> > @ffromani i have modified the test case to check with a gu pod which was the original issue.
> 
> thanks, but the main issue remains. I guess we don't have better approaches handy, though. We need to start doing these checks using supported APIs, like the podresources API

@ffromani okay so if i understand correctly we can use podResources API to fetch defaultCpuSet instead of reading the state file ? Is there any API documentation that i can refer to ?

**Review by ffromani — COMMENTED** [review]
/approve
/lgtm

migrating to podresources API will need nontrivial effort. For now we prefer to accept the tech debt in order to get the required coverage

**Pull request merged**
