### PR TITLE
Updating cluster-node-tuning-operator images to be consistent with new ART images

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Update things that the bot didn't

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Review by jmencak — APPROVED** [review]
Thank you for the PR, Eduardo.  AFAIR, the images in 50-operator.yaml don't even need to exist, they just need to match the links in image-references.  Also, the rhel7 dockerfile is no longer used and we may think about removing it.  But this PR seems good to me for consitency at the moment.

**Comment by jmencak** [comment]
Actually, shouldn't `registry.ci.openshift.org/ocp/4.6:base` be `registry.ci.openshift.org/ocp/4.8:base` now?
/lgtm cancel

**Comment by ArangoGutierrez** [comment]
@jmencak ready again for `lgtm`

**Comment by jmencak** [comment]
> @jmencak ready again for `lgtm`

@ArangoGutierrez  did you see my [comment](https://github.com/openshift/cluster-node-tuning-operator/pull/194#issuecomment-775763457) about 4.6/4.8?

**Comment by ArangoGutierrez** [comment]
> > @jmencak ready again for `lgtm`
> 
> @ArangoGutierrez did you see my [comment](https://github.com/openshift/cluster-node-tuning-operator/pull/194#issuecomment-775763457) about 4.6/4.8?

ha, no I didn't, will add that change

**Comment by jmencak** [comment]
/lgtm
Thank you for the PR, Ed!

**Pull request merged**
