### PR TITLE
Bug 1884287: Upgrade to klog v2.

### PR DESCRIPTION
**Pull request by jmencak**

### CODE REVIEW

**Comment by jmencak** [comment]
@kpouget , @dagrayvid this should ideally merge by this Friday, thanks!

**Review by kpouget — APPROVED** [review]
the patch changes `klog` from `v1.0.0` to `v2.3.0`, and most of the changes simply replace `import "k8s.io/klog"` by `import "k8s.io/klog/v2"`.

Looking at the discussions that happend in this PR:
https://github.com/kubernetes/kubernetes/pull/89717

I checked that:
- all the modules in `vendor` already use `v2`
- there are use of `if klog.V(x) {` for testing of verbosity level (it seems to be `if klog.V(x).Enabled() {` in `v2`)
and I can't find anything else that could hide issues, so:

/lgtm

Thanks Jiri for the PR!

**Comment by jmencak** [comment]
Thanks Kevin, much appreciated!

**Pull request merged**
