### PR TITLE
stalld: remove support for built-in stalld

### PR DESCRIPTION
**Pull request by jmencak**
NTO uses OS-shipped stalld as of OCP 4.10.  This is cleaner, more
secure and therefore preferred way shipping stalld.  Having old legacy
code (built-in support for stalld) complicates new features, such as
support for the HyperShift platform.  Remove it.

### CODE REVIEW

**Comment by fromanirh** [comment]
/lgtm
I surely like the direction, codewise seems fine

**Comment by dagrayvid** [comment]
Thanks Jiri. Looks good to me. It's not very often we get to enjoy a PR that is removing 300x more lines than it's adding :)

/approve

**Pull request merged**
