### PR TITLE
Bug 1769470: Use net.ipv4.conf.all.arp_announce=2 in the openshift profile.

### PR DESCRIPTION
**Pull request by abhat**
Adapting a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1758552 from
OCP 3.11.

### CODE REVIEW

**Comment by ashcrow** [comment]
Waiting on QE verification.

**Comment by abhat** [comment]
> Waiting on QE verification.
> 
> I see this is coming from 3.x, did this hit `master` already?

yes this is in master already. https://github.com/openshift/cluster-node-tuning-operator/pull/81

**Comment by mfojtik** [comment]
the master was QE verified, approving

**Pull request merged**
