### PR TITLE
OCPBUGS-19785: Set non-default UserAgent for easier debugging

### PR DESCRIPTION
**Pull request by jmencak**
Add non-default UserAgent when communicating with the API server to ease debugging.  See OCPBUGS-19351 for more detail.

### CODE REVIEW

**Comment by jmencak** [comment]
@wking thank you for pointing out the issue with the UserAgent in OCPBUGS-19351, this should address it.

**Comment by yanirq** [comment]
/lgtm
@jmencak  would it be useful to open a bug for this and downport it ? 
/hold in case other reviews are needed

**Comment by jmencak** [comment]
> would it be useful to open a bug for this and downport it ?

That's probably a good idea.  Let me do that.

**Comment by jmencak** [comment]
Looks like we're not getting any more reviews. Let's get this merged.
/hold cancel

**Comment by jmencak** [comment]
Hypershift test succeded with this PR in the past.
/retest

**Pull request merged**
