### PR TITLE
Fix wrong PAO upgrading kubelet test

### PR DESCRIPTION
**Pull request by marioferh**
"Should not override performance-addon-operator values"
is failing due mcp its not getting changes in profile.
Fix test as previous ones in order to correct execution

Signed-off-by: Mario Fernandez <mariofer@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
I think this is a good change, thanks. Could you please make sure we have all the changes made in the PAO repo in https://github.com/openshift-kni/performance-addon-operators/pull/861 and possibly add the other missing parts in this PR if needed?

**Comment by marioferh** [comment]
> I think this is a good change, thanks. Could you please make sure we have all the changes made in the PAO repo in [openshift-kni/performance-addon-operators#861](https://github.com/openshift-kni/performance-addon-operators/pull/861) and possibly add the other missing parts in this PR if needed?

this is the only gap I've seen

**Comment by fromanirh** [comment]
> > I think this is a good change, thanks. Could you please make sure we have all the changes made in the PAO repo in [openshift-kni/performance-addon-operators#861](https://github.com/openshift-kni/performance-addon-operators/pull/861) and possibly add the other missing parts in this PR if needed?
> 
> this is the only gap I've seen

Thanks. Then we're good to go.

**Comment by shajmakh** [comment]
> @shajmakh: #394 failed to apply on top of branch "release-4.10":
> 
> ```
> Applying: Fix wrong kubelet test
> Using index info to reconstruct a base tree...
> A	test/e2e/performanceprofile/functests/2_performance_update/kubelet.go
> Falling back to patching base and 3-way merge...
> CONFLICT (modify/delete): test/e2e/performanceprofile/functests/2_performance_update/kubelet.go deleted in HEAD and modified in Fix wrong kubelet test. Version Fix wrong kubelet test of test/e2e/performanceprofile/functests/2_performance_update/kubelet.go left in tree.
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 Fix wrong kubelet test
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

the cherry-pick in fact should be done in PAO repo

**Pull request merged**
