### PR TITLE
Bug 2024682: controller: update MC after application by TuneD

### PR DESCRIPTION
**Pull request by jmencak**
Tuned Profiles are created by NTO operator and updated by both the
operator and its operand.  The operand's updates are the source of truth
for information such as kernel command-line parameters and presence of
the stalld daemon.  The operator is informed about this via the status
field of the a Tuned Profile that corresponds to a given node.  Operator
updates are the source of truth about which TuneD profile should be
applied.

When a new cluster node is added (for example during a cluster
scale-up), a new Tuned Profile is created.  If the node is quickly added
to a MachinePool for which an NTO-managed MachineConfig already exists,
this addition will cause NTO to overwrite/update the MachineConfig with
data that is incorrectly initialized.  If the operand was too slow to
correct this update (typically during scale-ups when the operand was not
yet running), this would cause unnecessary reboots of nodes sharing the
same MachineConfigPool.

This PR fixes the behaviour above by letting the operator update the
NTO-managed MachineConfigs only once the newly requested Tuned Profile
configuration is successfully applied.

Other changes:
- `go mod vendor && go mod tidy`

Resolves rhbz#2024682

### CODE REVIEW

**Comment by jmencak** [comment]
I've successfully tested that this PR fixes  [rhbz#2024682](https://bugzilla.redhat.com/show_bug.cgi?id=2024682).  No flipping and updating ConfigMap with empty and real/calculated kernel arguments was found.  I've also successfully tested upgrade from: 4.7.49 to NTO with this fix and then further on to 4.8.  All seemed fine, no issues found.
/hold cancel
/assign @dagrayvid

**Comment by dagrayvid** [comment]
Thanks @jmencak. From my side, these changes look safe.

/lgtm

**Comment by jmencak** [comment]
**Backport risk assessment**

- [ ] If the Bugzilla associated with the PR has the "FastFix" keyword, the subjective assessment on the issue has already been done and a customer is impacted. These PRs should be prioritized for merge.
  - not applicable
- [x] For branches that are in the Maintenance lifecycle phase:
  - The bug is a critical fix, no reasonable workaround exists, and a recommendation for upgrade has been ruled out.
- [x] The bug has significant impact either through severity, reduction in supportability, or number of users affected.
  - yes
- [x] The severity field of the bug must be set to accurately reflect criticality.
  - bugzilla/severity-high
- [x] The PR is merged in the next newer release branch and the bug for that newer release is VERIFIED by QE.
  - yes
- [x] The PR’s description is well formed with user-focused release notes that state the bug number, impact, cause, and resolution. Where appropriate, it should also contain information about how a user can identify whether a particular cluster is affected.
  - yes

/label backport-risk-assessed

**Comment by jmencak** [comment]
@wabouhamad can we have cherry-pick-approved for this one?  It is a backport of [this one](https://github.com/openshift/cluster-node-tuning-operator/pull/295).

**Comment by jmencak** [comment]
@mrunalp  PTAL, happy to answer any questions.  This is also in an effort to reduce the risk of triggering `rpm-ostree` related BZs during 4.7 upgrades such as: rhbz#2075126.

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Pull request merged**
