### PR TITLE
[release-4.11] OCPBUGS-1567: E2E: Automate Offline CPUs feature

### PR DESCRIPTION
**Pull request by mrniranjan**
This is a manual cherry pick of Offline CPU's feature merged in [PR 380](https://github.com/openshift/cluster-node-tuning-operator/pull/380)

Signed-off-by: Niranjan M.R <mrniranjan@redhat.com>

### CODE REVIEW

**Comment by mrniranjan** [comment]
@marioferh can you review this PR please

**Comment by marioferh** [comment]
Please update the PR message with cherry pick info. Thanks

**Review by marioferh — COMMENTED** [review]
/lgtm

**Pull request merged**
