### PR TITLE
 [release-4.13] [manual] OCPBUGS-11336: e2e: profile updates tests revised

### PR DESCRIPTION
**Pull request by yanirq**
This is manual cherry-pick of https://github.com/openshift/cluster-node-tuning-operator/pull/600

replaces https://github.com/openshift/cluster-node-tuning-operator/pull/603

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
/lgtm

**Comment by ffromani** [comment]
```
   [It] /go/src/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go:661
  [FAILED] Unexpected error:
      <*errors.errorString | 0xc0003faeb0>: {
          s: "node=\"ci-op-qrp1ysss-01c11-x69v4-worker-a-frrpt\" stalld_pid=\"5280\" stalld is running when it shouldn't",
      }
      node="ci-op-qrp1ysss-01c11-x69v4-worker-a-frrpt" stalld_pid="5280" stalld is running when it shouldn't
  occurred
  In [AfterEach] at: /go/src/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go:707 @ 04/16/23 12:24:12.448 
```

we seen this already. _CAN_ be a legit bug.

**Comment by yanirq** [comment]
> ```
>    [It] /go/src/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go:661
>   [FAILED] Unexpected error:
>       <*errors.errorString | 0xc0003faeb0>: {
>           s: "node=\"ci-op-qrp1ysss-01c11-x69v4-worker-a-frrpt\" stalld_pid=\"5280\" stalld is running when it shouldn't",
>       }
>       node="ci-op-qrp1ysss-01c11-x69v4-worker-a-frrpt" stalld_pid="5280" stalld is running when it shouldn't
>   occurred
>   In [AfterEach] at: /go/src/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go:707 @ 04/16/23 12:24:12.448 
> ```
> 
> we seen this already. _CAN_ be a legit bug.

possibly related to https://github.com/openshift/cluster-node-tuning-operator/pull/604

**Comment by yanirq** [comment]
Since we are in co dependency scenario between https://github.com/openshift/cluster-node-tuning-operator/pull/604 and this PR  ci/prow/e2e-gcp-pao-updating-profile  lane can be overridden.
The risk for overriding this PR is low since this is a test improvement only PR.

/override ci/prow/e2e-gcp-pao-updating-profile

**Pull request merged**
