### PR TITLE
[release-4.13] [manual] OCPBUGS-17845: deflake ht aware test

### PR DESCRIPTION
**Pull request by Tal-or**
Manual cherry pick of: #744, #729 
for fixing the ht aware test.

### CODE REVIEW

**Comment by ffromani** [comment]
looks like the `vet` failure is legit

**Review by ffromani — APPROVED** [review]
/approve
/lgtm

**Comment by Tal-or** [comment]
@mrniranjan Could you please add the `cherry-pick-approved` label?

**Pull request merged**
