### PR TITLE
Adjusting the OWNERS file due to team changes.

### PR DESCRIPTION
**Pull request by jmencak**

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by jmencak** [comment]
> /override ci/prow/images

Turns out one can only override stuff that failed.  It would be good to skip the tests completely (not even start them).  Let's try again though and see what the bot thinks:
/override ci/prow/e2e-upgrade

**Comment by jmencak** [comment]
Aaah, ok, so it looks the job has to start:
/override ci/prow/e2e-aws-operator 
/override ci/prow/e2e-aws

**Pull request merged**
