### PR TITLE
[release-4.13][manual] OCPBUGS-11813: performance-profile: enable crun for high-performance runtime

### PR DESCRIPTION
**Pull request by ffromani**
CRI-O can be configured to use crun as its low-level container runtime by
appliying ContainerRuntimeConfig CR.

Here, we are enabling high-performance runtime class to run with crun as
well based on the information from the ContainerRuntimeConfig CR.

manual backport of #588

### CODE REVIEW

**Comment by ffromani** [comment]
/hold

WIP

**Comment by ffromani** [comment]
/hold cancel

the cherry-pick series seems correct

**Comment by jlojosnegros** [comment]
/retitle [release-4.13][manual] OCPBUGS-11813: performance-profile: enable crun for high-performance runtime

**Review by MarSik — APPROVED** [review]
/lgtm

**Pull request merged**
