### PR TITLE
Updating to the latest stalld v1.9.0.

### PR DESCRIPTION
**Pull request by jmencak**
Changes:
  - updated https://gitlab.com/rt-linux-tools/stalld.git to v1.9.0
    (8c6fe4b4da167086328fe7ed3c8681f985b68c37)

### CODE REVIEW

**Comment by jmencak** [comment]
@dagrayvid all tests passed, PTAL. Thank you!

**Comment by kpouget** [comment]
/lgtm

thanks for the update @jmencak :)

**Pull request merged**
