### PR TITLE
OCPBUGS-15044:e2e:irqbalance: applied condition exists

### PR DESCRIPTION
**Pull request by Tal-or**
There was a subtle bug in the previous implementaion, where if the `tunedv1.TunedProfileApplied` does not exits in the slice we still return `true`

This behavior is logically wrong.
We should return `true` only if the condition
was found and it's condition status is positive.

### CODE REVIEW

**Comment by Tal-or** [comment]
/hold
Depends on: https://github.com/openshift/cluster-node-tuning-operator/pull/729

**Review by ffromani — COMMENTED** [review]
another good catch!

/approve
/lgtm

**Comment by Tal-or** [comment]
> another good catch!
> 
> /approve /lgtm

A self-catch doesn't count ;)

**Comment by Tal-or** [comment]
/hold cancel
/test e2e-gcp-pao
 https://github.com/openshift/cluster-node-tuning-operator/pull/729 will be handled separately

**Pull request merged**
