### PR TITLE
TuneD: switch to FDP TuneD delivery

### PR DESCRIPTION
**Pull request by jmencak**
Switch to Fast Data Path (FDP) method of delivering TuneD.  Keep the old
method of delivery in place for emergency rollback and update the
version of TuneD to match the version current in the FDP channel.

### CODE REVIEW

**Comment by jmencak** [comment]
A few notes to reviewers:
- This should merge this week.
- `tuned-profiles-openshift, tuned-profiles-postgresql and tuned-profiles-spectrumscale` profiles are not shipped via CDN yet, therefore I decided to ship all profiles locally.  Once this is fixed, we'll switch to shipping all the profiles from CDN too.
- This might be a potentially breaking change for non `x86_64` architectures.  The odds are that they will not be, but we will not know until this is merged and the `Dockerfile.rhel8` reconciled with the downstream CI.  I'll keep an eye on this and take appropriate actions if/when things break.

**Comment by jmencak** [comment]
I think it is unlikely we're getting those missing 3 packages in CDN by the end of this week, therefore:
/retitle TuneD: switch to FDP TuneD delivery

**Comment by dagrayvid** [comment]
Thanks @jmencak for the PR. The changes make sense (after discussing on slack).

/lgtm

**Pull request merged**
