### PR TITLE
update owners 20230109

### PR DESCRIPTION
**Pull request by ffromani**
Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by jmencak** [comment]
So who's this "new" guy :)
/lgtm

**Review by MarSik — APPROVED** [review]
/lgtm

Francesco renamed his account.

**Review by swatisehgal — COMMENTED** [review]
/lgtm

**Comment by ffromani** [comment]
> New changes are detected. LGTM label has been removed.

rebased

**Comment by jmencak** [comment]
I believe it is time to:
/override ci/prow/e2e-gcp-pao-updating-profile

**Comment by ffromani** [comment]
> I believe it is time to: /override ci/prow/e2e-gcp-pao-updating-profile

thanks! we still have work to do in this area.

**Comment by jmencak** [comment]
Huh
/override ci/prow/e2e-gcp-pao-updating-profile
/retest

**Pull request merged**
