### PR TITLE
WIP: enable control of the verbosiness of the operand

### PR DESCRIPTION
**Pull request by ffromani**
WIP TBD

### CODE REVIEW

**Comment by jmencak** [comment]
Thank you for the PR, Francesco.

I can see a couple of disadvantages with this approach.

1) An extra API call to get a config map.
2) Unability to chage verbosity per operand (this would cause a restart of all NTO operands, not just the ones we are interested in).

While the current way of turning on debugging for operands (TuneD) is not ideal, I believe we probably want something along the lines of what we already have:

```
  recommend:
    operand:
      debug: true
```

and perhaps add something like:
```
  recommend:
    operand:
      debug: true
      verbosity: <number>
```

This might even enable us not to restart the operand/TuneD at all and thus have less impact on the cluster?

**Comment by ffromani** [comment]
shouldn't we need to change the DaemonSet manifest anyway?

**Comment by jmencak** [comment]
> shouldn't we need to change the DaemonSet manifest anyway?

Why?  Wouldn't we just pick up the verbosity from the profile, like we do debugging?  I haven't tried though, so perhaps there are some technical difficulties I'm not seeing.

**Comment by ffromani** [comment]
ok, sounds fair to me. We'll see in a future PR then.

**Comment by jmencak** [comment]
> ok, sounds fair to me. We'll see in a future PR then.

Let me look into that or whoever gets there first...

**Comment by jmencak** [comment]
Alternative approach: https://github.com/openshift/cluster-node-tuning-operator/pull/1114

**Pull request closed without merging**
