### PR TITLE
Revert "Revert PAO and later changes"

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Reverts openshift/cluster-node-tuning-operator#330

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@cynepco3hahue the original change for this broke hypershift, because the `node-tuning-operator_50-operator-ibm-cloud-managed.yaml` manifest references the `apiservice-cert` from the service in `45-webhook-configuration.yaml` which isn't deployed on Hypershift because it lacks the `include.release.openshift.io/ibm-cloud-managed: "true"` annotation. Could you please add that annotation there or not reference the secret in `node-tuning-operator_50-operator-ibm-cloud-managed.yaml`?

**Comment by cynepco3hahue** [comment]
> @cynepco3hahue the original change for this broke hypershift, because the `node-tuning-operator_50-operator-ibm-cloud-managed.yaml` manifest references the `apiservice-cert` from the service in `45-webhook-configuration.yaml` which isn't deployed on Hypershift because it lacks the `include.release.openshift.io/ibm-cloud-managed: "true"` annotation. Could you please add that annotation there or not reference the secret in `node-tuning-operator_50-operator-ibm-cloud-managed.yaml`?

Thanks for the comment, I will revisit changes related to the `ibm-cloud-managed` annotation.

**Comment by yanirq** [comment]
/lgtm
this is a combination of the 3 already approved PRs.

/cc @jmencak  please take a look and we can check if https://github.com/openshift/origin/pull/26944 will require further alignments after this PR is merged.

**Comment by jmencak** [comment]
After testing for an hour on an idle cluster, I'm seeing:

```
$ kubectl-dev_tool audit \
    --after 2022-04-04T08:20:22+02:00 \
    -f all.log -otop --verb=watch --by resource --user=system:serviceaccount:openshift-cluster-node-tuning-operator:cluster-node-tuning-operator

count: 141, first: 2022-04-04T08:20:37+02:00, last: 2022-04-04T09:20:23+02:00, duration: 59m45.925201s
18x                  tuned.openshift.io/tuneds
18x                  machineconfiguration.openshift.io/v1/machineconfigpools
17x                  v1/nodes
15x                  tuned.openshift.io/profiles
15x                  machineconfiguration.openshift.io/v1/machineconfigs
9x                   machineconfiguration.openshift.io/v1/kubeletconfigs
9x                   apps/daemonsets
9x                   node.k8s.io/v1beta1/runtimeclasses
9x                   performance.openshift.io/v2/performanceprofiles
8x                   tuned.openshift.io/v1/profiles
```

vs. cluster without this PR:

```
$ kubectl-dev_tool audit \
    --after 2022-04-04T10:24:30+02:00 \
    -f all.log -otop --verb=watch --by resource --user=system:serviceaccount:openshift-cluster-node-tuning-operator:cluster-node-tuning-operator

count: 61, first: 2022-04-04T10:26:45+02:00, last: 2022-04-04T11:25:30+02:00, duration: 58m44.954911s
10x                  v1/nodes
9x                   apps/daemonsets
9x                   config.openshift.io/v1/clusteroperators
9x                   tuned.openshift.io/profiles
8x                   machineconfiguration.openshift.io/v1/machineconfigs
8x                   tuned.openshift.io/tuneds
8x                   machineconfiguration.openshift.io/v1/machineconfigpools
```

The watch count is cca 2.3 higher now.  I couldn't see any short watches during the idle run.

/approve
/hold
@deads2k , please unhold if you're happy with the current situation.

**Comment by deads2k** [comment]
> The watch count is cca 2.3 higher now. I couldn't see any short watches during the idle run.

excellent!

/hold cancel

**Pull request merged**
