### PR TITLE
Bump to golang 1.16 and various vendor deps.

### PR DESCRIPTION
**Pull request by jmencak**
For a list of changed dependencies, please see `go.mod`.

### CODE REVIEW

**Comment by jmencak** [comment]
Untested, let the tests pass first.

**Review by ArangoGutierrez — APPROVED** [review]
latest is my favorite version
/lgtm
leaving it on hold since 1 test hasn't pass yet
/hold

**Comment by jmencak** [comment]
/retest
operator tests are passing and that is important to, cancelling hold
/hold cancel

**Comment by dagrayvid** [comment]
@jmencak @ArangoGutierrez should the Dockerfiles also be changed to go 1.16?

**Comment by jmencak** [comment]
> @jmencak @ArangoGutierrez should the Dockerfiles also be changed to go 1.16?

Thanks David, changed the upstream `Dockerfile`.  However, this will have no influence over the CI.

**Comment by jmencak** [comment]
Let's hear a 
/joke

**Review by ArangoGutierrez — APPROVED** [review]
Good catch on the dockerfile @dagrayvid 
/lgtm

**Comment by dagrayvid** [comment]
> > @jmencak @ArangoGutierrez should the Dockerfiles also be changed to go 1.16?
> 
> Thanks David, changed the upstream `Dockerfile`. However, this will have no influence over the CI.

Is this because the FROM line will be substituted in the CI anyway?

**Comment by jmencak** [comment]
> Is this because the FROM line will be substituted in the CI anyway?

No, this is because the [CI uses](https://github.com/openshift/release/blob/bebfd104458815f66618b686a5d33405116a39c1/ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml#L56) `Dockerfile.rhel8`.  The 'replaced anyway' holds true for the ART CI, not the one used here.

**Comment by dagrayvid** [comment]
> > Is this because the FROM line will be substituted in the CI anyway?
> 
> No, this is because the [CI uses](https://github.com/openshift/release/blob/bebfd104458815f66618b686a5d33405116a39c1/ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml#L56) `Dockerfile.rhel8`. The 'substituted anyway' holds true for the ART CI, not the one used here.

Thanks for clarifying!

**Pull request merged**
