### PR TITLE
Fix a race in e2e test rollback.go code

### PR DESCRIPTION
**Pull request by jmencak**
This changes fixes a race between a sysctl write and TuneD applying a profile.

### CODE REVIEW

**Comment by jmencak** [comment]
As the only NTO reviewer is on PTO
/cc @yanirq 
Yanir, this should address the occasional glitches in e2e-aws-operator test introduced recently during code changes that make TuneD not roll-back settings on exit.  Thanks!

We should probably backport.

**Comment by yanirq** [comment]
/lgtm
Failures in PAO lanes are unrelated (they should eventually be fixed with https://github.com/openshift/cluster-node-tuning-operator/pull/737 (or an equivalent effort)
Failing lanes can be overridden if needed

**Comment by jmencak** [comment]
Thank you, Yanir.
/retest

**Pull request merged**
