### PR TITLE
NO-JIRA: 4.16 go deps

### PR DESCRIPTION
**Pull request by jmencak**
This change bumps go dependencies prior to 4.16 release and updates k8s dependencies to 1.29.4.

```
What I've done:

$ go get -u ./...
$ # pin all dependencies so that the project compiles and tests pass
$ go mod tidy
$ go mod vendor
```

### CODE REVIEW

**Comment by jmencak** [comment]
This is a change that should merge prior to 26th April in my view. I've tried to clean up `go.mod` and bump as many dependencies as possible.  As the bot-suggested reviewers are off, inviting
/cc @swatisehgal 
/cc @ffromani 
for review.

**Review by ffromani — COMMENTED** [review]
/lgtm
/hold

we need to update our code to catch uop with `ghw` changes

**Comment by jmencak** [comment]
Unholding so that this can pass through the (hypershift and other) e2e tests and merge by Friday...
/hold cancel

**Pull request merged**
