### PR TITLE
OCPBUGS-16908: Add SetLogger() prior to controller-runtime start

### PR DESCRIPTION
**Pull request by jmencak**
Adding `SetLogger()` fixes debug stack trace dump issued by controller-runtime 0.15.0:
https://github.com/kubernetes-sigs/controller-runtime/blob/36bb89936b37aca36ba4ad34760f4879db97dba2/pkg/log/log.go#L59

Resolves: OCPBUGS-16908

### CODE REVIEW

**Comment by jmencak** [comment]
Example of a fixed trace:
```
I0901 15:31:07.670265       1 leaderelection.go:255] successfully acquired lease openshift-cluster-node-tuning-operator/node-tuning-operator-lock
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 109 [running]:
runtime/debug.Stack()
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
        /go/src/github.com/openshift/cluster-node-tuning-operator/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:59 +0xbd
sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc00048f740, 0x10?)
        /go/src/github.com/openshift/cluster-node-tuning-operator/vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:111 +0x3d
github.com/go-logr/logr.Logger.Enabled(...)
        /go/src/github.com/openshift/cluster-node-tuning-operator/vendor/github.com/go-logr/logr/logr.go:261
github.com/go-logr/logr.Logger.Info({{0x222c878?, 0xc00048f740?}, 0x0?}, {0xc0000573e0, 0x60}, {0xc0005db9e0, 0x6, 0x6})
        /go/src/github.com/openshift/cluster-node-tuning-operator/vendor/github.com/go-logr/logr/logr.go:274 +0x78
sigs.k8s.io/controller-runtime/pkg/internal/recorder.(*Provider).getBroadcaster.func1.1(0xc0000fef00)
        /go/src/github.com/openshift/cluster-node-tuning-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/recorder/recorder.go:104 +0x1ed
k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
        /go/src/github.com/openshift/cluster-node-tuning-operator/vendor/k8s.io/client-go/tools/record/event.go:327 +0xa2
created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
        /go/src/github.com/openshift/cluster-node-tuning-operator/vendor/k8s.io/client-go/tools/record/event.go:318 +0x13d

```

**Comment by yanirq** [comment]
/lgtm
I am not  adding the critical fixes label yet, it should be considered carefully at this stage.

**Comment by jmencak** [comment]
> I am not adding the critical fixes label yet, it should be considered carefully at this stage.

This shouldn't really break anything, it just gets rid of the annoying dump.  I take full responsibility.  Let's get it in.
/label acknowledge-critical-fixes-only

**Pull request merged**
