### PR TITLE
Allow new cri-o annotations for power management config

### PR DESCRIPTION
**Pull request by bartwensley**
Adding the following new cri-o annotations to the list of allowed
annotations in the crio.runtime.runtimes.high-performance configuration:
- cpu-c-states.crio.io
- cpu-freq-governor.crio.io

These annotations were added to crio-o with this PR:
https://github.com/cri-o/cri-o/pull/5927

Signed-off-by: Bart Wensley <bwensley@redhat.com>

### CODE REVIEW

**Comment by yanirq** [comment]
since you changed the content of [99-runtimes.conf](https://github.com/openshift/cluster-node-tuning-operator/pull/383/files#diff-e763c8f403f44cd298b79a200633f6e687c478a00bda33b0d85e0add10eeb60b)  you will have to adjust the encoded content here https://github.com/openshift/cluster-node-tuning-operator/blob/191024dc4a3722bed5b7a917c6e4342a927aa129/test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml#L60 so the test will be able to match the 2

**Comment by bartwensley** [comment]
@yanirq and @jlojosnegros - the tests are passing now - please review this when you have time. Thanks!!!

**Pull request merged**
