### PR TITLE
Ship the latest TuneD, adjust default Tuned CR.

### PR DESCRIPTION
**Pull request by jmencak**
This PR ships the latest TuneD daemon 2.16.0-0.1.rc1.

Other changes:
  - adjust the openshift-tuned code to reflect the upstream project renaming
  - adjust the default Tuned CR to work with kernels 5.13+ (see rhbz#1952687)

### CODE REVIEW

**Comment by jmencak** [comment]
Do not merge, yet.  Wait for the official `v2.16.0` upstream tag and rebase.  Other thant that, it should be good to go.
/retitle WiP: Ship the latest TuneD, adjust default Tuned CR.

**Comment by kpouget** [comment]
Hey @jmencak, thanks for the PR!
> adjust the default Tuned CR to work with kernels 5.13+ (see rhbz#1952687)

I don't understand what hunk is doing this, could you give a link to this is change?

**Comment by jmencak** [comment]
Flake.
/retest

**Comment by jmencak** [comment]
> Hey @jmencak, thanks for the PR!
> 
> > adjust the default Tuned CR to work with kernels 5.13+ (see rhbz#1952687)
> 
> I don't understand what hunk is doing this, could you give a link to this is change?

It is the changes in the `default-cr-tuned.yaml` file.

**Comment by jmencak** [comment]
Let's get this tested in 4.9 as soon as we can to discover real issues.

/override ci/prow/e2e-upgrade 
/retitle Ship the latest TuneD, adjust default Tuned CR.

**Comment by ArangoGutierrez** [comment]
Tried and tested
/lgtm

**Comment by ArangoGutierrez** [comment]
```bash
Ran 3 of 3 Specs in 1340.902 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestNodeTuningOperator (1340.90s)
PASS
ok      github.com/openshift/cluster-node-tuning-operator/test/e2e/reboots      1340.915s
```

**Comment by jmencak** [comment]
e2e-upgrade (s) are failing at the moment, that's a known issue, but try too
/test e2e-upgrade

**Comment by jmencak** [comment]
> e2e-upgrade (s) are failing at the moment, that's a known issue, but try too
> /test e2e-upgrade

/override e2e-upgrade

**Pull request merged**
