### PR TITLE
Modify owners file

### PR DESCRIPTION
**Pull request by marioferh**
Modify owners file

### CODE REVIEW

**Comment by ffromani** [comment]
uhm, we still require a `valid-bug` label :\

**Comment by jmencak** [comment]
> uhm, we still require a `valid-bug` label :\

Yeah, this is annoying.  I thought that it would go away today.

**Comment by kpouget** [comment]
`e2e-hypershift` [failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-node-tuning-operator/634/pull-ci-openshift-cluster-node-tuning-operator-master-e2e-hypershift/1661465283023343616) might be a flake, retrying
/test e2e-hypershift

**Review by MarSik — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
