### PR TITLE
NO-JIRA: Remove removePerformanceOLMOperator()

### PR DESCRIPTION
**Pull request by jmencak**
Removing the removePerformanceOLMOperator() code and associated CSV tests as they are unnecessarily taking too long now.

### CODE REVIEW

**Comment by jmencak** [comment]
There is probably more code to be removed in the PPC-controler specific bits.  I wonder if you can help with that @yanirq . Removing the NTO-specific parts what make NTO e2e take tests unnecessarily long.  Thank you!

**Comment by jmencak** [comment]
Infra issues.
/retest

**Comment by yanirq** [comment]
https://github.com/openshift/cluster-node-tuning-operator/blob/master/pkg/performanceprofile/controller/utils.go can be removed as well

**Comment by yanirq** [comment]
> There is probably more code to be removed in the PPC-controler specific bits. I wonder if you can help with that @yanirq . Removing the NTO-specific parts what make NTO e2e take tests unnecessarily long. Thank you!

code removal in regards to OLM operator ? or in general ?

**Comment by jmencak** [comment]
> code removal in regards to OLM operator

code removal in regards to OLM operator

**Comment by yanirq** [comment]
I don't see any changes required on performance profile creator.
There are still a few items to remove (e2e test, olm uneeded schems additions) , basically revert https://github.com/openshift/cluster-node-tuning-operator/pull/346  - probably went a bit through changes but these are the main places where this code needs to be cleaned up.

**Comment by yanirq** [comment]
I think we can also update go.sum/modules/vendor  files

**Comment by jmencak** [comment]
> I think we can also update go.sum/modules/vendor files

Done, ran "go mod tidy && go mod vendor"

**Pull request merged**
