### PR TITLE
OCPBUGS-30812: Ignore scheduler plugin IRQs when globally enabled

### PR DESCRIPTION
**Pull request by yanirq**
Disable irq affinity setting by scheduler plugin ONLY when GloballyDisableIrqLoadBalancing=false (default)

### CODE REVIEW

**Comment by yanirq** [comment]
> /lgtm
> 
> the e2e-no-cluster failure is legit, you probably need to run `make render-sync`

The reason for the missing sync is https://github.com/openshift/cluster-node-tuning-operator/pull/980  . until its merged I added the missing changes manually.

**Review by MarSik — APPROVED** [review]
/lgtm

**Comment by MarSik** [comment]
/retitle OCPBUGS-30812: Ignore scheduler plugin IRQs when globally enabled

**Pull request merged**
