### PR TITLE
Bug 1719967: Implement leader-for-life election.

### PR DESCRIPTION
**Pull request by jmencak**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1719967

### CODE REVIEW

**Comment by jmencak** [comment]
@zvonkok , mind taking a look in Sebastian's absense? Thanks!

**Comment by zvonkok** [comment]
The same approach as here: https://github.com/zvonkok/special-resource-operator/blob/a065b27c1aa9219b3960a8ea47069754a5533920/cmd/manager/main.go#L56 
and this works if multiple instances of the operator are running, one is leader and the other ones are "only"  waiting to become leader. 

/lgtm

**Pull request merged**
