### PR TITLE
OCPBUGS-44644:  [release-4.17] PPC: skip comparing ProcessorCore.Index between NUMA cores

### PR DESCRIPTION
**Pull request by shajmakh**
…ores  (#1213)
manual backport and typo fixes of #1213

### CODE REVIEW

**Comment by shajmakh** [comment]
/cherry-pick release-4.16 release-4.15 release-4.14 release-4.13 release-4.12

**Comment by shajmakh** [comment]
hypershift lane is flaky due to a known issue and the hypershift team is aware about
/test e2e-hypershift

**Review by ffromani — COMMENTED** [review]
/approve
/lgtm

**Comment by ffromani** [comment]
/retitle OCPBUGS-44644:  [release-4.17] PPC: skip comparing ProcessorCore.Index between NUMA cores

**Comment by shajmakh** [comment]
to _fix_ the bug completely we need 3 PRs so closing this in favor https://github.com/openshift/cluster-node-tuning-operator/pull/1252. I'll still be following the normal flow of backporting so will wait for 4.18 batch to be merged first.

**Pull request closed without merging**
