### PR TITLE
Changing pattern & small build changes

### PR DESCRIPTION
**Pull request by sjug**
WIP

What do you think @jmencak about the syncDaemonSet. I changed the secondary watch as well but it still doesn't work yet. Will expand to monitor the whole cluster.

Suggest rolling out a similar sync to the other objects to short circuit on get, and update after comparison.

### CODE REVIEW

**Comment by sjug** [comment]
At this point all sync functions except the configmaps are following the new get first pattern. Also they do not update as we should to find a way to compare and see if it's necessary. Owner references throughout so deletion of the CRD cleans up nicely enough.

**Comment by jmencak** [comment]
Thanks for the PR!  So at this point I see this a little bit as a step backwards, as the updates are no longer performed.  I can see the benefit of setting the SetControllerReference though.  Can you add the updates to the PR, please?  Thanks.

**Comment by sjug** [comment]
@jmencak Sure, I've added updates back.

**Pull request merged**
