### PR TITLE
Revert "Tighten the rules for modifying Tuned Profiles (#765)"

### PR DESCRIPTION
**Pull request by neisw**
This reverts commit 561d9ae80b34c9196707d20d4752fb93474f1b0a.

[OCPBUGS-17972](https://issues.redhat.com/browse/OCPBUGS-17972) further documents this issue.

TRT is observing 10 out of 10 jobs showing the tuning operator is degraded in the latest nightly [4.14.0-0.nightly-2023-08-22-042716](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-08-22-042716) aggregation run for [gcp-ovn-rt-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-gcp-ovn-rt-upgrade-4.14-minor-release-openshift-release-analysis-aggregator/1693843205704912896).

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), and given the time constraints as we look to get successful payload we are opening this revert to attempt to run payload jobs against it to see if we can observe the issue or not with this code reverted.

We have opened OCPBUGS-17972 to track the issue and will update / reassign based on our finding

The root issue we are chasing is 
`

: [sig-node] nodes should not go unready after being upgraded and go unready only once expand_less | 0s
-- | --
{  1 nodes violated upgrade expectations:  Node ci-op-yqt1rfy5-d5fb3-528j8-worker-a-rstbv went unready multiple times: 2023-08-22T06:27:18Z, 2023-08-22T06:31:43Z, 2023-08-22T07:03:23Z Node ci-op-yqt1rfy5-d5fb3-528j8-worker-a-rstbv went ready multiple times: 2023-08-22T06:27:39Z, 2023-08-22T06:32:21Z, 2023-08-22T07:04:22Z  }

`

We believe this PR broke the `[sig-node] nodes should not go unready after being upgraded and go unready only once` test which is now failing on nightly payloads for periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade/.

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run techpreview jobs on the unrevert:

/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade/

### CODE REVIEW

**Comment by neisw** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade 10

**Comment by jmencak** [comment]
/cc @dagrayvid 
just incase approval is needed today.  However, I do not see how https://github.com/openshift/cluster-node-tuning-operator/commit/561d9ae80b34c9196707d20d4752fb93474f1b0a could cause the issues reported.

**Comment by neisw** [comment]
The [NOOP PR](https://github.com/openshift/cluster-node-tuning-operator/pull/772) and subsequent nightly payloads continue to show the issue.  The payload-jobs on this revert do not.  Discussed with Jiri and we will proceed with the revert.

**Pull request merged**
