### PR TITLE
TuneD: use the same FDP version for upstream

### PR DESCRIPTION
**Pull request by jmencak**
Downstream project currently ships TuneD 70732a57, bump it for the upstream.

Signed-off-by: Jiri Mencak <jmencak@users.noreply.github.com>

### CODE REVIEW

**Comment by jmencak** [comment]
@yanirq can you please take a look?  You're familiar with the reasons for this, we discussed this yesterday.  Thank you!

**Comment by yanirq** [comment]
/lgtm
lets also have an approval from @dagrayvid :
/hold

**Comment by dagrayvid** [comment]
Looks good to me, thanks.

/unhold

**Pull request merged**
