### PR TITLE
OCPBUGS-14026: cgroup: Match the name of the cgroup to what is expected by kubelet

### PR DESCRIPTION
**Pull request by swatisehgal**
Ensure consistent naming of system cgroup in order to ensure that it matches cgroup name expected by Kubelet.

### CODE REVIEW

**Comment by yanirq** [comment]
@swatisehgal  you might need to align the render command tests (see failing job for ci/prow/e2e-no-cluster)

**Comment by yanirq** [comment]
/retitle OCPBUGS-14026: cgroup: Match the name of the cgroup to what is expected by kubelet

**Comment by Tal-or** [comment]
Is it possible to add an e2e for verifying the fix?

**Comment by swatisehgal** [comment]
/hold
The fix needs to be verified.

**Comment by swatisehgal** [comment]
/unhold

As @browsell has verified the fix. We will defer adding the e2e test in a follow-up PR.

**Pull request merged**
