### PR TITLE
CNF-9664: cpuset-configure: exit gracefully on cgroup v2

### PR DESCRIPTION
**Pull request by haircommander**

### CODE REVIEW

**Comment by MarSik** [comment]
@haircommander We rely on systemd to create the system.slice now, right? The old code was just because the cpuset controller was not managed by systemd.

**Comment by haircommander** [comment]
> We rely on systemd to create the system.slice now, right? The old code was just because the cpuset controller was not managed by systemd

yeah, systemd will enable the cpuset controller now

**Comment by MarSik** [comment]
@haircommander You need to update the tests. There is a Makefile target for that (render-sync)

**Comment by MarSik** [comment]
/retitle CNF-9664: cpuset-configure: exit gracefully on cgroup v2

**Pull request merged**
