### PR TITLE
OCPBUGS-19351: Revert "Release leader election on manager exit

### PR DESCRIPTION
**Pull request by sdodson**
This reverts commit 8f21a273b3ff4ff21a15b9bdcc59ffa788be559b.

### CODE REVIEW

**Comment by sdodson** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-ovn-rt-upgrade 4

**Comment by jmencak** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-ovn-rt-upgrade 4

**Comment by sdodson** [comment]
@jmencak I'm inclined to move forward with this revert since the other of the two suspect changes did have successful payload jobs run prior to merge, thoughts on that plan?

**Comment by sdodson** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-ovn-rt-upgrade 4

**Comment by sdodson** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-ovn-rt-upgrade 10

**Comment by sdodson** [comment]
/retitle OCPBUGS-19351: Revert "Release leader election on manager exit

**Comment by sdodson** [comment]
/retest-required
Build problems due to rpm service down and build cluster infra issues

**Comment by ffromani** [comment]
/override ci/prow/e2e-gcp-pao-updating-profile 

known issue which should be fixed by this revert proper

**Comment by ffromani** [comment]
> /override ci/prow/e2e-gcp-pao-updating-profile
> 
> known issue which should be fixed by this revert proper

or build cluster issue (still unrelated)

**Comment by ffromani** [comment]
it seems the bot is super-slow/misbehaving

**Comment by jmencak** [comment]
This doesn't fix https://issues.redhat.com/browse/OCPBUGS-19351, reverting the revert.

**Comment by jmencak** [comment]
The real fix: https://github.com/openshift/cluster-node-tuning-operator/pull/803

**Comment by jmencak** [comment]
@sdodson I believe that some action connected with this change left an upstream branch [revert-773-4.13-OCPBUGS-18000-leader-lease-release](https://github.com/openshift/cluster-node-tuning-operator/tree/revert-773-4.13-OCPBUGS-18000-leader-lease-release) around which I cannot delete.  Any idea how to remove [that branch](https://github.com/openshift/cluster-node-tuning-operator/tree/revert-773-4.13-OCPBUGS-18000-leader-lease-release) or who can?  Thank you!

**Comment by sdodson** [comment]
@jmencak I've deleted the branch

**Pull request merged**
