### PR TITLE
[release-4.15][manual] OCPBUGS-29396: Labels for e2e testing 

### PR DESCRIPTION
**Pull request by Tal-or**
backport of:
* https://github.com/openshift/cluster-node-tuning-operator/pull/947
* https://github.com/openshift/cluster-node-tuning-operator/pull/936

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
/approve
/lgtm

**Comment by Tal-or** [comment]
/retest
This PR cannot affect any of the test since it's an API proposal which not being used yet.

**Pull request merged**
