### PR TITLE
NO-JIRA: Update OWNERS file

### PR DESCRIPTION
**Pull request by jmencak**
David and Kevin are both no longer involved in this project. Make sure we don't spam them with review requests.

/cc @dagrayvid 
/cc @kpouget

### CODE REVIEW

**Comment by dagrayvid** [comment]
Thanks Jiri!
/lgtm

**Comment by jmencak** [comment]
Putting a
/hold
for @kpouget to unhold.

**Comment by kpouget** [comment]
Thanks Jiri for the PR, and bye-bye & good luck NTO 👋🏻 💟 

/hold cancel

**Pull request merged**
