### PR TITLE
OCPBUGS-47658: [release-4.16][manual]: Fix context deadlines in ExecCommandOnPod()

### PR DESCRIPTION
**Pull request by Tal-or**
Manual and partial backport of https://github.com/openshift/cluster-node-tuning-operator/pull/1189

### CODE REVIEW

**Comment by Tal-or** [comment]
We should backport this PR up until 4.14.

I see similar symptoms in: https://github.com/openshift-kni/cnf-features-deploy/pull/2135

**Comment by Tal-or** [comment]
/hold cancel 
It does

**Comment by jmencak** [comment]
Thank you for the backport.
/lgtm
/approve
/backport-risk-assessed

**Pull request merged**
