### PR TITLE
NO-JIRA:e2e:labels: fix typo and adding type

### PR DESCRIPTION
**Pull request by Tal-or**
small typo fixes and added a missing type declaration.

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
are we breaking backward compat somehow by fixing these consts?

**Comment by Tal-or** [comment]
> are we breaking backward compat somehow by fixing these consts?

@mrniranjan do you know if these labels are already used on our existing tests?

**Comment by mrniranjan** [comment]
> > are we breaking backward compat somehow by fixing these consts?
> 
> @mrniranjan do you know if these labels are already used in our existing tests?

Not yet ,  but we do want to use these for our testing

**Comment by ffromani** [comment]
great, so let's fix them quick-quick :)

**Pull request merged**
