### PR TITLE
OCPBUGS-4194:  Use appropriate device path  for rpsmask test

### PR DESCRIPTION
**Pull request by mrniranjan**
When using mco pod to execute find command to search for bridges we use /rootfs/sys/devices

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
/lgtm
/approve
/hold

waiting for @Tal-or 's review
note: this is _not_ a refactor, rather a code change

**Comment by Tal-or** [comment]
/test e2e-upgrade
infra issue

**Pull request merged**
