### PR TITLE
Upgrading to operator-sdk 0.4.0

### PR DESCRIPTION
**Pull request by jmencak**
@sjug PTAL

### CODE REVIEW

**Comment by sjug** [comment]
Tested and working. Didn't seem to need that many changes to the actual operator `pkg/`?

**Comment by jmencak** [comment]
@sjug, not sure which changes you're talking about, but the e2e tests were not working without a few more changes.  If you're talking about the extra cleanup, then yes, this PR is not about just the upgrade, but cleanup too.

**Comment by sjug** [comment]
@jmencak I'm talking about the changes to the operator code which were needed in order to update to the operator-sdk v0.4.0.

**Pull request merged**
