### PR TITLE
  Add build and ppc test invocation under one target

### PR DESCRIPTION
**Pull request by yanirq**
Add build and ppc test targets under `test-e2e-local`
that already contains the render test so there will be one main
target for local e2e tests.

### CODE REVIEW

**Comment by yanirq** [comment]
This PR will correspond with https://github.com/openshift/release/pull/27797

**Comment by jmencak** [comment]
The title seems a bit misleading to me.  You're just adding dependencies to a target, right?

**Comment by yanirq** [comment]
> The title seems a bit misleading to me. You're just adding dependencies to a target, right?

Right, but making the test-e2e-local the main target to be triggered by the CI lane, also for future non cluster e2e tests.
At the moment there are only 2.

**Comment by yanirq** [comment]
> The title seems a bit misleading to me. You're just adding dependencies to a target, right?

@jmencak  commit title changed

**Comment by jmencak** [comment]
Thank you for the change, Yanir.
/lgtm

**Pull request merged**
