### PR TITLE
Bug 1962219: Switch to client-go leader-with-lease election.

### PR DESCRIPTION
**Pull request by jmencak**
Previously, NTO relied on the operator-sdk (leader-for-life) way of
handling leader election.  The leader-for-life was implemented by
relying on k8s garbage collector mechanism the same way as implemented
by operator-sdk.  Unfortunately, practise shows (rhbz#1916865,
rhbz#1958885) this is not reliable as the ConfigMap locks are sometimes
not garbage collected.

Therefore, switch to leader-with-lease election mechanism as provided by
the client-go package, which seems to be more reliable at this point.

Other changes:
  - fix incorrect error reporting on metrics server shutdown
  - fix default_irq_smp_affinity e2e test for systems with less than 4 CPUs

### CODE REVIEW

**Comment by jmencak** [comment]
Tested by doing operator upgrades and also by shutting down a node.

**Comment by jmencak** [comment]
@ArangoGutierrez , @dagrayvid would you be able to provide a review? Thanks guys!

**Comment by jmencak** [comment]
Temporarili assigned myself as QE to overcome the bot issues above.
/bugzilla refresh

**Comment by ArangoGutierrez** [comment]
PR looking good, I have no comments on the implementation, my comment goes to `make test-e2e` is failing for me, maybe I am doing it wrong? 

```
• Failure [306.113 seconds]
[basic][default_irq_smp_affinity] Node Tuning Operator set irq default smp affinity
/home/eduardo/sdk/github/openshift/cluster-node-tuning-operator/test/e2e/basic/default_irq_smp_affinity.go:20
  irq default smp affinity
  /home/eduardo/sdk/github/openshift/cluster-node-tuning-operator/test/e2e/basic/default_irq_smp_affinity.go:29
    default_irq_smp_affinity: /proc/irq/default_smp_affinity set [It]
    /home/eduardo/sdk/github/openshift/cluster-node-tuning-operator/test/e2e/basic/default_irq_smp_affinity.go:44

    Unexpected error:
        <*errors.errorString | 0xc0004bc260>: {
            s: "command [grep -o .$ /proc/irq/default_smp_affinity] outputs 1 (leading/trailing whitespace trimmed) in Pod tuned-sht78, expected d: <nil>",
        }
        command [grep -o .$ /proc/irq/default_smp_affinity] outputs 1 (leading/trailing whitespace trimmed) in Pod tuned-sht78, expected d: <nil>
    occurred

    /home/eduardo/sdk/github/openshift/cluster-node-tuning-operator/test/e2e/basic/default_irq_smp_affinity.go:83
------------------------------
SSSSSSSS

Summarizing 1 Failure:

[Fail] [basic][default_irq_smp_affinity] Node Tuning Operator set irq default smp affinity irq default smp affinity [It] default_irq_smp_affinity: /proc/irq/default_smp_affinity set 
/home/eduardo/sdk/github/openshift/cluster-node-tuning-operator/test/e2e/basic/default_irq_smp_affinity.go:83

Ran 4 of 12 Specs in 347.724 seconds
FAIL! -- 3 Passed | 1 Failed | 0 Pending | 8 Skipped
--- FAIL: TestNodeTuningOperator (347.72s)
FAIL
FAIL    github.com/openshift/cluster-node-tuning-operator/test/e2e/basic        347.735s
FAIL
make: *** [Makefile:91: test-e2e] Error 1
```

**Comment by jmencak** [comment]
> PR looking good, I have no comments on the implementation, my comment goes to `make test-e2e` is failing for me, maybe I am doing it wrong?
> 
> ```
> • Failure [306.113 seconds]
> [basic][default_irq_smp_affinity] Node Tuning Operator set irq default smp affinity
> /home/eduardo/sdk/github/openshift/cluster-node-tuning-operator/test/e2e/basic/default_irq_smp_affinity.go:20
>   irq default smp affinity
>   /home/eduardo/sdk/github/openshift/cluster-node-tuning-operator/test/e2e/basic/default_irq_smp_affinity.go:29
>     default_irq_smp_affinity: /proc/irq/default_smp_affinity set [It]
>     /home/eduardo/sdk/github/openshift/cluster-node-tuning-operator/test/e2e/basic/default_irq_smp_affinity.go:44
> 
>     Unexpected error:
>         <*errors.errorString | 0xc0004bc260>: {
>             s: "command [grep -o .$ /proc/irq/default_smp_affinity] outputs 1 (leading/trailing whitespace trimmed) in Pod tuned-sht78, expected d: <nil>",
>         }
>         command [grep -o .$ /proc/irq/default_smp_affinity] outputs 1 (leading/trailing whitespace trimmed) in Pod tuned-sht78, expected d: <nil>
>     occurred
> 
>     /home/eduardo/sdk/github/openshift/cluster-node-tuning-operator/test/e2e/basic/default_irq_smp_affinity.go:83
> ------------------------------
> SSSSSSSS
> 
> Summarizing 1 Failure:
> 
> [Fail] [basic][default_irq_smp_affinity] Node Tuning Operator set irq default smp affinity irq default smp affinity [It] default_irq_smp_affinity: /proc/irq/default_smp_affinity set 
> /home/eduardo/sdk/github/openshift/cluster-node-tuning-operator/test/e2e/basic/default_irq_smp_affinity.go:83
> 
> Ran 4 of 12 Specs in 347.724 seconds
> FAIL! -- 3 Passed | 1 Failed | 0 Pending | 8 Skipped
> --- FAIL: TestNodeTuningOperator (347.72s)
> FAIL
> FAIL    github.com/openshift/cluster-node-tuning-operator/test/e2e/basic        347.735s
> FAIL
> make: *** [Makefile:91: test-e2e] Error 1
> ```

Thanks for looking and testing, Ed, much appreciated!  While I'm certain this has nothing to do with the PR itself, I've had issues with this e2e test on different architectures (Xen vs. KVM for example) in the past.  Could you paste the entire output of the test (a few lines above the failure) or at least the contents of `/proc/irq/default_smp_affinity` prior the test and also `lscpu -p`?  Thank you!

**Comment by jmencak** [comment]
@ArangoGutierrez , the `default_irq_smp_affinity` should now be fixed for systems with less than 4 CPUs.  Please let me know if you see other issues.  Thanks!

**Review by ArangoGutierrez — APPROVED** [review]
Patch looks good to me

**Comment by jmencak** [comment]
Great, thanks for the comment @ArangoGutierrez .  If this looks good then, `/lgtm` label appreciated from either of you Ed/Simon.

**Pull request merged**
