### PR TITLE
Bug 1880348: Bump to k8s 1.18.9 to fix bug in reflector not recovering from "Too large resource version"

### PR DESCRIPTION
**Pull request by jmencak**
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1880348

### CODE REVIEW

**Comment by jmencak** [comment]
@sjug PTAL, thank you.

**Comment by jmencak** [comment]
@sjug PTAL

**Comment by markmc** [comment]
/retitle Bump to k8s 1.18.9 to fix bug in reflector not recovering from "Too large resource version"

**Comment by markmc** [comment]
/retitle Bug 1880348: Bump to k8s 1.18.9 to fix bug in reflector not recovering from "Too large resource version"

**Pull request merged**
