### PR TITLE
Bug 1986739: gather all Tuned CRs

### PR DESCRIPTION
**Pull request by jmencak**
Fixes gathering all of Tuned CRs with oc adm inspect/must-gather.

### CODE REVIEW

**Comment by kpouget** [comment]
makes sense after looking at the BZ, we want to catch all the `tuned` objects
/lgtm

thanks @jmencak for the PR!

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

picked

**Pull request merged**
