### PR TITLE
OCPBUGS-12229: e2e: add missing test id

### PR DESCRIPTION
**Pull request by shajmakh**
Add missing PAO test id to enble proper reporting of the test's result.

### CODE REVIEW

**Review by ffromani — APPROVED** [review]
/approve
/lgtm

**Comment by shajmakh** [comment]
timed out waiting for mcp.
/retest

**Comment by ffromani** [comment]
@shajmakh because of the stage we are in the development cycle, turns out you need a bug even for such a simple fix

**Pull request merged**
