### PR TITLE
feat: library-go bump

### PR DESCRIPTION
**Pull request by eggfoobar**
Bumping the library-go dependency to latest, this should take advantage of leader election changes for SNO clusters proposed in this [library-go PR](https://github.com/openshift/library-go/pull/1242).

Changes:
  - updated library go to latest
  - moved leader election config to util pkg
  - updated to use leader election configs from library-go

Signed-off-by: ehila <ehila@redhat.com>

### CODE REVIEW

**Comment by yanirq** [comment]
> /cc @yanirq something to be aware of that needs to be supported by the future NTO/PAO rewrite/merge.

rewrite will need to be rebase. Movement of PAO will contain this update (https://github.com/openshift-kni/performance-addon-operators/pull/467)

**Comment by jmencak** [comment]
Thank you for the PR, @eggfoobar , however this doesn't seem to be working as expected at the moment.  Tested on a HA cluster and SNO cluster and seeing HA cluster leader election values in both cases.
```
W1214 12:41:11.705444       1 leaderelection.go:30] unable to get cluster infrastructure status, using HA cluster values for leader election: infrastructures.config.openshift.io "cluster" is forbidden: User "system:serviceaccount:openshift-cluster-node-tuning-operator:cluster-node-tuning-operator" cannot get resource "infrastructures" in API group "config.openshift.io" at the cluster scope
```
Sounds like some perms are missing.

**Review by jmencak — CHANGES_REQUESTED** [review]
Thank you for the PR, this seems to work for me after the following change:
```
--- a/manifests/40-rbac.yaml
+++ b/manifests/40-rbac.yaml
@@ -48,9 +48,10 @@ rules:
 - apiGroups: [""]
   resources: ["nodes/metrics","nodes/specs"]
   verbs: ["get"]
-# Needed by every CVO-managed operator.
+# clusteroperators are needed by every CVO-managed operator,
+# infrastructures by the leader election code.
 - apiGroups: ["config.openshift.io"]
-  resources: ["clusteroperators"]
+  resources: ["clusteroperators", "infrastructures"]
   verbs: ["create","get","list","watch"]
 # Needed by every CVO-managed operator.
 - apiGroups: ["config.openshift.io"]
```

**Comment by eggfoobar** [comment]
Thanks so much @jmencak ! Removing the WIP

**Comment by jmencak** [comment]
> Thanks so much @jmencak ! Removing the WIP

No worries, will you push the fix and squash so that I can approve this?  Thank you!

**Comment by eggfoobar** [comment]
Absolutely, updated :)

**Comment by jmencak** [comment]
Retested.

/lgtm
/approve

**Pull request merged**
