### PR TITLE
Use Ignition 3 for MachineConfigs.

### PR DESCRIPTION
**Pull request by jmencak**
MCO in OCP 4.6 will use Ignition 3 by default.  Follow the same path.

### CODE REVIEW

**Comment by jmencak** [comment]
@sjug / @kpouget  PTAL
Thanks!

**Comment by jmencak** [comment]
Thank you Kevin, much appreciated.  Any chance of a lgtm label if you feel this is OK?

**Comment by kpouget** [comment]
\lgtm

**Comment by jmencak** [comment]
Don't think bot picks up edits.  But thanks!

/lgtm
^ based on message above.

**Comment by jmencak** [comment]
Nice, it used to be possible to /lgtm own PRs. Good to know!

**Comment by kpouget** [comment]
/lgtm

I'm always bad with these IRC-like messages :# :# :# ;-)

and I *think* I already approved the PR when I validated my review:
>  kpouget approved these changes 4 days ago 
but we'll see if this lgtm changes something or not

**Comment by jmencak** [comment]
> but we'll see if this lgtm changes something or not

It does, many thanks!  Time to pray for CI tests to pass again.

**Comment by kpouget** [comment]
> > but we'll see if this lgtm changes something or not
> 
> It does, many thanks! Time to pray for CI tests to pass again.

great, so "lgtm" and "approved" tags are not the same, I'll know it for next time :)

**Comment by jmencak** [comment]
> great, so "lgtm" and "approved" tags are not the same, I'll know it for next time :)

They're not and only folk listed as [approvers](https://github.com/openshift/cluster-node-tuning-operator/blob/920e69b9c169d9165efc4f864faefca1c53406dc/OWNERS#L1) can add an "approved" label to a PR.

**Pull request merged**
