### PR TITLE
OCPBUGS-14148: e2e: perfprof: add SNO device recovery test (#653)

### PR DESCRIPTION
**Pull request by shajmakh**
manual cherry-pick of https://github.com/openshift/cluster-node-tuning-operator/pull/653

### CODE REVIEW

**Comment by shajmakh** [comment]
should override https://github.com/openshift/cluster-node-tuning-operator/pull/664#

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Comment by shajmakh** [comment]
/assign @yanirq 
for approval and missing labels

**Pull request merged**
