### PR TITLE
[release-4.14] OCPBUGS-30153: fix rendering extra ctrcfgs

### PR DESCRIPTION
**Pull request by vitus133**
This is a manual cherry-pick of #975 
Fix bootstrap error  of "more than one ContainerRuntimeConfig found that matches MCP labels" when an additional ContainerRuntimeConfig is provided by user.

/cc @yanirq @MarSik

### CODE REVIEW

**Comment by yanirq** [comment]
/retitle [release-4.14] OCPBUGS-30153: fix rendering extra ctrcfgs

**Review by MarSik — APPROVED** [review]

**Comment by mrniranjan** [comment]
@vitus133 can you rebase and update the Release Note on the bug. I have verified 4.15 bug.

**Comment by yanirq** [comment]
Test failure for  ci/prow/e2e-no-cluster  needs a look:
`   [FAIL] render command e2e test With performance profile and matching extra ContainerRuntimeConfig during bootstrap [It] should render ContainerRuntimeConfig
  /go/src/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go:193 `

**Comment by vitus133** [comment]
@mrniranjan @yanirq Needs cherry-pick-approved, lgtm labels :)

**Pull request merged**
