### PR TITLE
NO-JIRA: deps: Bump OCP dependencies and remove MCO deps

### PR DESCRIPTION
**Pull request by swatisehgal**
1. Bump OCP deps
2. Remove MCO deps

Based on top of: https://github.com/openshift/cluster-node-tuning-operator/pull/990

### CODE REVIEW

**Comment by hexfusion** [comment]
Seems like there is still some instability in the build clusters.

/test e2e-gcp-pao-workloadhints

**Comment by hexfusion** [comment]
> Init container initupload not ready: (state: terminated, reason: "Error", message: "026uploadType=multipart\\\": oauth2: cannot fetch token: 400 Bad Request\\nResponse: 

This appears to be a problem from CI itself

/test e2e-gcp-pao

**Comment by hexfusion** [comment]
> Job execution failed: Terminal error: nonretryable error: no build client found for cluster "build03".

:(

**Comment by hexfusion** [comment]
@swatisehgal looks like TestPerformanceKubelet is failing which could be related to this bump can you take a look?

**Comment by jmencak** [comment]
e2e-gcp-pao-updating-profile already passed today with the same code today, let's get this merged.
/override ci/prow/e2e-gcp-pao-updating-profile

**Pull request merged**
