### PR TITLE
OCPBUGS-24929: Use go 1.21

### PR DESCRIPTION
**Pull request by jmencak**
Changed go.mod and ran "go mod tidy".

Also see: https://github.com/openshift/cluster-node-tuning-operator/pull/873

### CODE REVIEW

**Comment by ffromani** [comment]
do we require matching changes in `openshift/release`?

**Comment by jmencak** [comment]
> do we require matching changes in `openshift/release`?

I already [did some](https://github.com/openshift/release/pull/46678), but to be honest, not sure that's all.

**Comment by ffromani** [comment]
> > do we require matching changes in `openshift/release`?
> 
> I already [did some](https://github.com/openshift/release/pull/46678), but to be honest, not sure that's all.

fair enough. Let's see what CI thinks and then we'll see how to move forward.

**Comment by ffromani** [comment]
/lgtm

CI likes it, and seems fine to me.

**Pull request merged**
