### PR TITLE
Revert 773 and 766

### PR DESCRIPTION
**Pull request by sdodson**
This PR is in case it's only at the intersection of 773 and 766 that the problem exists.

### CODE REVIEW

**Comment by sdodson** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-ovn-upgrade

**Comment by jmencak** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-ovn-upgrade

**Comment by jmencak** [comment]
Please do not revert, the real fix: https://github.com/openshift/cluster-node-tuning-operator/pull/803

**Pull request closed without merging**
