### PR TITLE
Revert "Tighten the rules for modifying Tuned Profiles (#766)"

### PR DESCRIPTION
**Pull request by sdodson**
This reverts commit 45ba0908008e59c3ded0db1be7e2af2469e8e2c2.

### CODE REVIEW

**Comment by sdodson** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-ovn-upgrade

**Comment by sdodson** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-ovn-rt-upgrade 4

**Comment by sdodson** [comment]
Given the original PR where this merged had payload jobs passing it seems unlikely that this is the offending change. See https://github.com/openshift/cluster-node-tuning-operator/pull/766#issuecomment-1705205051

**Comment by jmencak** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-ovn-rt-upgrade 4

**Comment by jmencak** [comment]
Please do not revert, the real fix: https://github.com/openshift/cluster-node-tuning-operator/pull/803

**Comment by jmencak** [comment]
This has been addressed by https://github.com/openshift/cluster-node-tuning-operator/pull/803
/close

**Pull request closed without merging**
