### PR TITLE
NO-JIRA: e2e-test: Call SetLogger to avoid controller-runtime error.

### PR DESCRIPTION
**Pull request by jlojosnegros**
You must set a logger for controller-runtime, otherwise it complains.

### CODE REVIEW

**Comment by jmencak** [comment]
Thank you for the change.
/approve
/lgtm

**Comment by ffromani** [comment]
/lgtm

what about the other suites? are them good?

**Comment by jmencak** [comment]
> /lgtm
> 
> what about the other suites? are them good?

They don't use controller-runtime, at least not in core NTO.

**Comment by jlojosnegros** [comment]
> /lgtm
> 
> what about the other suites? are them good?

It seems so. 
I managed to reproduce the issue using a time.Sleep(45 seconds) on the affected test suite, so I did the same with all the other e2e test suites and no one got affected, so I assume they are ok.

**Comment by ffromani** [comment]
I suspect the perfprof suites may hit the same issue, but since I don't have any hard data to back my claim, I guess it's fine like it is now.

**Pull request merged**
