### PR TITLE
Remove Dockerfile.rhel7 no longer needed

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
remove Dockerfile.rhel7 for OCP 4.8+ versions, no longer supported

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by jmencak** [comment]
Thank you for the PR, Eduardo.
/lgtm
/hold
until https://github.com/openshift/cluster-node-tuning-operator/pull/194 merges

**Comment by jmencak** [comment]
/hold cancel
@ArangoGutierrez needs rebase, sorry.

**Comment by jmencak** [comment]
/lgtm cancel
in the hope the bot relaxes and stops retesting a PR that has a merge conflict

**Comment by ArangoGutierrez** [comment]
Interesting, rebase to get changes on a file I am about to delete.... I thought Git was smarter than this

**Comment by ArangoGutierrez** [comment]
Rebased @jmencak

**Review by jmencak — APPROVED** [review]
Thank you for the PR, Eduardo.
/lgtm

**Pull request merged**
