### PR TITLE
Bug 2078969: Ignore Profile updates triggered by old operands

### PR DESCRIPTION
**Pull request by jmencak**
Depending on TuneD configuration and version, TuneD may calculate
different kernel command-line parameters for the same TuneD profile.
This is a problem during NTO operator upgrades.  The old (still running)
and newly started NTO operands (already running with newer version of
TuneD) will compete to push their specific version of calculated kernel
command-line parameters.  The new version will always win, but this
"competition" may trigger extra unwanted node reboots.

This change prevents the operator from accepting the
MachineConfig-specific changes from old (not-yet-upgraded) operands.
This prevents the NTO-generated MachineConfigs from being flipped
between the old and new versions of kernel command-line parameters.

Other changes:
  - Fix a potential SEGV when a Profile fails to be retrieved by the
    operand.

Resolves rhbz#2078969.

### CODE REVIEW

**Comment by jmencak** [comment]
/cc @dagrayvid 
Additional info.  I've noticed this issue yesterday when upgrading from 4.8->4.9 and using `realtime` profile (other upgrades up to 4.11 were fine).  We need to get this backported to at least 4.9 (that will fix the 4.8->4.9 upgrade issue).  Didn't see any issues from 4.7->4.8 upgrades, but ideally, I'd like to backport this to 4.8 too.

**Comment by jmencak** [comment]
Infra issues.
```
error: timed out waiting for the condition on clusteroperators/network
```
/joke
/retest

**Comment by jmencak** [comment]
Infra issues `Cluster operator monitoring is not available`. I'm not going to and waste any more money on retesting until this is reviewed. @dagrayvid could you please take a look?  Thank you!

**Comment by dagrayvid** [comment]
Thanks Jiri. These fixes looks good to me.

/lgtm

**Comment by jmencak** [comment]
```
Failed to wait for bootstrapping to complete. 
```
/retest

**Comment by jmencak** [comment]
Bot, please give me a favour and once this merges
/cherry-pick release-4.10

**Pull request merged**
