### PR TITLE
pao e2e: fix stalld enablement checks

### PR DESCRIPTION
**Pull request by yanirq**
util functions for checking stalld proccess existance fixed since they were existing the check too early due to hidden errors.

### CODE REVIEW

**Review by jmencak — COMMENTED** [review]
Overall looks good, definitely an improvement over what we had, thank you.
Let's see if the tests pass, fix the nit and merge.

**Comment by jmencak** [comment]
We've hit the 5h timeout again.

**Comment by yanirq** [comment]
/hold
https://github.com/openshift/cluster-node-tuning-operator/pull/626 to probably include this fix as well in one PR

**Comment by mrniranjan** [comment]
@yanirq please use OCPBUGS-11083 for this PR.

**Comment by yanirq** [comment]
close in favor of https://github.com/openshift/cluster-node-tuning-operator/pull/626

**Pull request closed without merging**
