### PR TITLE
Fix RPS e2e test condition

### PR DESCRIPTION
**Pull request by yanirq**
RPS e2e test never actually ran since the enter condition was wrong

### CODE REVIEW

**Comment by mrniranjan** [comment]
Looks good to me

**Comment by mrniranjan** [comment]
@yanirq We addressed this condition in another patch https://github.com/openshift/cluster-node-tuning-operator/pull/483

**Comment by yanirq** [comment]
close in favor of https://github.com/openshift/cluster-node-tuning-operator/pull/483

**Pull request closed without merging**
