### PR TITLE
use GA kubelet OS label

### PR DESCRIPTION
**Pull request by rphillips**
ref: https://jira.coreos.com/browse/POD-114

### CODE REVIEW

**Comment by jmencak** [comment]
Thanks Ryan! Looks good, but this shouldn't be merged before 1.15 rebase, right?

**Comment by rphillips** [comment]
@jmencak This is fine to merge now, since 0.14.x also includes the change.

**Comment by jmencak** [comment]
gathered that might be the case looking at k8s PR73048, thanks for the confirmation
/lgtm

**Pull request merged**
