### PR TITLE
Bug 2018053: tuned: add timeout and restarts

### PR DESCRIPTION
**Pull request by jmencak**
TuneD profile application typically takes ~0.5s and should never take
more than ~5s.  However, there were cases where TuneD daemon got stuck
during application of a profile.  Experience shows that subsequent
restarts of TuneD can resolve this in certain situations.  TuneD itself,
however, has no mechanism for restarting a profile application that is
taking too long.

This change implements full restarts for TuneD daemon.

Other changes:
  - tunedStop() is now fully synchronous.  Previously, when TuneD
    refused to terminate within 10s, SIGKILL was sent without waiting
    for TuneD process to terminate.

Also see: rhbz#2013940

### CODE REVIEW

**Comment by dagrayvid** [comment]
Thanks @jmencak. This looks good to me.

/lgtm

**Comment by jmencak** [comment]
**Backport risk assessment**

- [ ] If the Bugzilla associated with the PR has the "FastFix" keyword, the subjective assessment on the issue has already been done and a customer is impacted. These PRs should be prioritized for merge.
  - not applicable
- [ ] For branches that are in the Maintenance lifecycle phase:
  - not applicable
- [x] The bug has significant impact either through severity, reduction in supportability, or number of users affected.
  - yes
- [x] The severity field of the bug must be set to accurately reflect criticality.
  - bugzilla/severity-high
- [x] The PR is merged in the next newer release branch and the bug for that newer release is VERIFIED by QE.
  - yes
- [x] The PR’s description is well formed with user-focused release notes that state the bug number, impact, cause, and resolution. Where appropriate, it should also contain information about how a user can identify whether a particular cluster is affected.
  - yes

**Comment by jmencak** [comment]
@wabouhamad , can we get cherry-pick-approved?  Many thanks!

**Pull request merged**
