### PR TITLE
Fixup cluster operator resource

### PR DESCRIPTION
**Pull request by derekwaynecarr**
This PR does the following:

1. bump openshift/api,client-go,library-go dependencies
1. rename clusteroperator resource to node-tuning
1. add relatedObjects to node-tuning so openshift/must-gather can pull diagnostic data for troubleshooting
1. add clusteroperator resource to manifest so it is knowable by cvo during rollout

see: https://github.com/openshift/must-gather

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
why is e2e-aws not enabled on this repo?

/hold

**Comment by derekwaynecarr** [comment]
until e2e-aws is enabled on this repo, no prs should merge.

see: https://github.com/openshift/release/pull/2829

/cc @jeremyeder

**Comment by jmencak** [comment]
Many thanks for the PR.
/lgtm

**Comment by jmencak** [comment]
https://github.com/openshift/release/pull/2829 merged, I think the hold can be canceled, @derekwaynecarr

**Pull request merged**
