### PR TITLE
Bug 1963866: Bump vendor dependencies to k8s 1.21.1

### PR DESCRIPTION
**Pull request by jmencak**
Changes:
  - vendor dependencies to k8s 1.21.1
  - latest OpenShift and MCO dependencies
  - bump up x/text dependency

### CODE REVIEW

**Comment by jmencak** [comment]
This is a Friday evening PR, it should be OK, but give it more testing on Monday.
/hold

**Comment by kpouget** [comment]
image

/joke

lol :#

;-)

**Comment by jmencak** [comment]
/hold cancel
All tests succeeded, but let's give it another round of testing, especially 
/test ci/prow/e2e-aws-operator

**Comment by jmencak** [comment]
All tests passed, e2e-aws-operator retested twice. Looks good from where I am. Kevin/David, can I have a review?

**Comment by kpouget** [comment]
/lgtm

thanks Jiri :)

**Pull request merged**
