### PR TITLE
e2e: devmgr: fine tune kubelet restart test

### PR DESCRIPTION
**Pull request by ffromani**
address pending comments from #697

### CODE REVIEW

**Comment by shajmakh** [comment]
thanks for this tuning!
I don't have lgtm permissions though, but certainly lgtm.

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Comment by ffromani** [comment]
/override ci/prow/e2e-hypershift 
/override ci/prow/e2e-aws-ovn

this change can't break either, as we are doing minor fixes to a test which doesn't run unless explicitely enabled (and we don't in CI)

**Pull request merged**
