### PR TITLE
Allow selective debugging of the Tuned daemon.

### PR DESCRIPTION
**Pull request by jmencak**
Added an option allowing a per-node or per-MachineConfigGroup
debugging of the Tuned daemon.  The Tuned daemon has several
options which are currently not exposed by NTO.  This is the
first one to be exposed for users.

Fixes:
  - Consistency/Capitalization fixes as per instructions from the
    upstream Tuned project (Tuned daemon/profile).

### CODE REVIEW

**Comment by jmencak** [comment]
@courtneypacheco PTAL

**Comment by jmencak** [comment]
Had to rebase because of the merged metrics PR.

**Review by courtneypacheco — APPROVED** [review]
Confirmed that the debug statements show up and function as intended.

\lgtm

**Comment by jmencak** [comment]
> Confirmed that the debug statements show up and function as intended.
> 
> /lgtm

Thank you for the review, @courtneypacheco .  Edited comments will not be picked up by the bot.  If you want to add the LGTM label, we need a fresh '/lgtm' comment.

**Pull request merged**
