### PR TITLE
Revert "OCPNODE-1539: perf profile: add script for preparing cgroups for CPU load balance disabling"

### PR DESCRIPTION
**Pull request by DennisPeriquet**
Reverts openshift/cluster-node-tuning-operator#601

Per [TRT policy](https://github.com/openshift/enhancements/blob/5180e5873f5d5aca4fe4678882602a0c7f083a63/enhancements/release/improving-ci-signal.md#quick-revert), we reverting this change to get ci and/or nightly payloads flowing again.

Since this was merged, the aggregated-gcp-ovn-rt-upgrade-4.14-minor blocking job in 4.14 nightly payload has been failing (as tracked in [TRT-982](https://issues.redhat.com//browse/TRT-982)).

To get this reverted PR back in, please make a new PR unreverting this PR with your fixes layered on top.

To confirm it is working, run `/payload 4.14 nightly blocking` as a test.
cc: @haircommander

### CODE REVIEW

**Comment by MarSik** [comment]
@DennisPeriquet This is a fix for a 4.13 blocker issue that MUST be in. It can't be reverted.

**Comment by DennisPeriquet** [comment]
this revert does not solve the problem.

**Pull request closed without merging**
