### PR TITLE
NO-JIRA: revert: remove 4.13->4.14 compatibility code (#1079)"

### PR DESCRIPTION
**Pull request by ffromani**
This reverts commit aae3135a3dab198ff2503cd98ad37bd854c8d6dd.

Since #1079 was merged too quickly because the bot missed the "hold" command, I'm posting a revert so we can discuss

### CODE REVIEW

**Comment by Tal-or** [comment]
/hold
/lgtm

Adding due to https://github.com/openshift/cluster-node-tuning-operator/pull/1079#issuecomment-2158071511

**Comment by Tal-or** [comment]
@ffromani feel free to unhold, I just added the hold to avoid what just happened in the original PR

**Comment by ffromani** [comment]
I still think the original PR has merit, so we should NOT merge this revert, but let's discuss

**Comment by bartwensley** [comment]
@MarSik - I didn't work on the feature, but I believe @eggfoobar did

**Comment by eggfoobar** [comment]
Oh hey! Yeah this should be removed by now, the migration was for 4.13->4.14, this all went GA 4.14 if I remember correctly, so we should be good to remove it. Only issue would be someone jumping from 4.13 to 4.17, which to my knowledge we have no way of supporting that high of a jump correct?

**Comment by ffromani** [comment]
So, I understand we do _not_ want this revert because we are happy with the compat check removed, right?
@eggfoobar @MarSik @yanirq

**Comment by eggfoobar** [comment]
Yeah that's my understanding, unless we ran into an issue I'm not aware of, this code should be past it's usefulness and we don't want this code back in master.

**Comment by ffromani** [comment]
/close

peer feedback and conversations

**Pull request closed without merging**
