### PR TITLE
[release-4.15][manual] OCPBUGS-29376: Mixed CPUs e2e tests

### PR DESCRIPTION
**Pull request by Tal-or**
Manual backport of:
* https://github.com/openshift/cluster-node-tuning-operator/pull/892 
* https://github.com/openshift/cluster-node-tuning-operator/pull/912 
* https://github.com/openshift/cluster-node-tuning-operator/pull/914

### CODE REVIEW

**Comment by Tal-or** [comment]
/hold

Tests are falling - investigating

**Comment by Tal-or** [comment]
/hold 
Depends on #912

**Comment by yanirq** [comment]
/label backport-risk-assessed

non blocking tests , separated from payload

**Review by ffromani — COMMENTED** [review]
/lgtm

**Pull request merged**
