### PR TITLE
Revert "Updating to the latest stalld v1.13.0."

### PR DESCRIPTION
**Pull request by stbenjam**
This reverts commit bebd346838e960aaaf97cb509b9bb17539ca9c82, testing
the possible impact on upgrades.

### CODE REVIEW

**Review by jmencak — COMMENTED** [review]
What upgrade failures are you seeing, @stbenjam ?  Stalld is not even used by default in a regular cluster and has to be enabled.  Typically by other operators such as PAO.  Therefore I *highly* doubt https://github.com/openshift/cluster-node-tuning-operator/commit/bebd346838e960aaaf97cb509b9bb17539ca9c82 has anything to do with upgrade failures you mention.

**Comment by stbenjam** [comment]
> What upgrade failures are you seeing, @stbenjam ? Stalld is not even used by default in a regular cluster and has to be enabled. Typically by other operators such as PAO. Therefore I _highly_ doubt [bebd346](https://github.com/openshift/cluster-node-tuning-operator/commit/bebd346838e960aaaf97cb509b9bb17539ca9c82) has anything to do with upgrade failures you mention.

Ah ok, thanks for the information -- you're probably right then. 

We're investigating GCP upgrade failures that started around 7/12. There was only a handful of commits and this was one of them.

**Comment by jmencak** [comment]
> > What upgrade failures are you seeing, @stbenjam ? Stalld is not even used by default in a regular cluster and has to be enabled. Typically by other operators such as PAO. Therefore I _highly_ doubt [bebd346](https://github.com/openshift/cluster-node-tuning-operator/commit/bebd346838e960aaaf97cb509b9bb17539ca9c82) has anything to do with upgrade failures you mention.
> 
> Ah ok, thanks for the information -- you're probably right then.
> 
> We're investigating GCP upgrade failures that started around 7/12. There was only a handful of commits and this was one of them.

No worries, this PR triggered a race in my e2e tests -- will fix it.  So it was actually useful. :)

**Comment by jmencak** [comment]
This is the first time I actually don't mind seeing `ci/prow/e2e-upgrade` failure.

**Comment by jmencak** [comment]
Can we have this PR closed @stbenjam , as this didn't "fix" the `ci/prow/e2e-upgrade` issues?  Thank you!

**Comment by deads2k** [comment]
/reopen

Since we're upgrading from a level which (may) have a flawed stalld, wouldn't we expect to continue seeing failures because the starting level has an issue?

**Comment by deads2k** [comment]
> /reopen
> 
> Since we're upgrading from a level which (may) have a flawed stalld, wouldn't we expect to continue seeing failures because the starting level has an issue?

For a more accurate test, we'd want to have a 4.7.z direct to this PR upgrade test, not a failing level to this PR.

**Comment by jmencak** [comment]
> > /reopen
> > Since we're upgrading from a level which (may) have a flawed stalld, wouldn't we expect to continue seeing failures because the starting level has an issue?
> 
> For a more accurate test, we'd want to have a 4.7.z direct to this PR upgrade test, not a failing level to this PR.

Do the upgrade tests use `stalld`?  Do they create any conffig for NTO that causes it to use `stalld`?  If not, this PR is not even using the functionality and I don't see how it can influence the upgrade tests.

**Comment by jmencak** [comment]
I believe this can be
/close
-d now?

**Pull request closed without merging**
