### PR TITLE
OCPBUGS-18949: Tighten the rules for modifying Tuned Profiles

### PR DESCRIPTION
**Pull request by jmencak**
NTO operands allow updating Tuned Profiles.  This is intentional and by design as some host information needs to be communicated back to the NTO operator, but this also allows a successful local attacker potentially affect node-level configuration of other cluster nodes.

This change addresses the situation in two ways.  First, scoped RBAC permissions on Profile.status subresource is used to disallow Node-level write access to Profile.spec.  Second, the Node resource is used to provide status loops back to NTO using the kubelet credential to write an annotation to the Node resource.

This change also simplifies the mechanism for accepting kernel command-line parameters as calculated by the NTO operands.  Now, all NTO operands must agree on the calculated kernel command-line parameters.

ClusterOperator/node-tuning now also reports operand version.  The operand version changes only when all operand replicas have successfully upgraded and are ready.  This information is used to block PPC Reconcilation loop until the operator and operand RELEASE_VERSION agree. This is a short-term measure to prevent from multiple node reboots during upgrades.

Other fixes:
  - Disallow MC updates during upgrades when kernel command-line parameters of nodes within a MCP do not match.
  - ClusterOperator/node-tuning object was sometimes giving false information based on an old Metadata.Generation.

Resolves: OCPBUGS-18949

### CODE REVIEW

**Comment by jmencak** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-gcp-ovn-rt-upgrade 10

**Comment by sdodson** [comment]
/hold
We're observing a regression in node reboots during upgrades in https://issues.redhat.com/browse/OCPBUGS-19351 while we sort out which of the two changes in 4.13 triggered this (https://github.com/openshift/cluster-node-tuning-operator/pull/773 or https://github.com/openshift/cluster-node-tuning-operator/pull/766) put this on hold.

**Comment by sdodson** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-gcp-ovn-upgrade

**Comment by jmencak** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-gcp-ovn-upgrade

**Comment by jmencak** [comment]
/hold
see https://issues.redhat.com/browse/OCPBUGS-19795

**Comment by jmencak** [comment]
/hold cancel
Fix for https://issues.redhat.com/browse/OCPBUGS-19795 added.

**Comment by jmencak** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-gcp-ovn-upgrade

**Comment by jmencak** [comment]
> @jmencak: trigger 1 job(s) for the /payload-(job|aggregate) command
> 
>     * periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-gcp-ovn-upgrade
> 
> 
> See details on https://pr-payload-tests.ci.openshift.org/runs/ci/2226a4c0-5e95-11ee-865a-d3cf8fb84dd9-0

/cc @dagrayvid 
David, not urgent, but when you have a minute, PTAL.  All tests including the 4.12-upgrade-from-stable-4.11-e2e-gcp-ovn-upgrade succeeded. Also, I've incorporated the fix for the [ROKS issue](https://issues.redhat.com/browse/OCPBUGS-19795).  This should also address [the issues](https://redhat-internal.slack.com/archives/CQNBUEVM2/p1695976438068729) with customers placing nodes with different topologies in the same MCP on 4.12.

**Comment by jmencak** [comment]
Need to test on HyperShift
/hold

**Comment by jmencak** [comment]
I did basic functionality testing of this on HyperShift.
/hold cancel

**Comment by dagrayvid** [comment]
Thanks @jmencak!

/lgtm

**Comment by jmencak** [comment]
/label backport-risk-assessed
@liqcui , can we please have cherry-pick-approved label for this?  Thank you!

**Pull request merged**
