### PR TITLE
Rename pao folders to performanceprofile

### PR DESCRIPTION
**Pull request by yanirq**
Folders changed from `pao` to `performanceprofile`:
```
examples/performanceprofile
pkg/performanceprofile
pkg/apis/performanceprofile
test/e2e/performanceprofile
assets/performanceprofile
```

### CODE REVIEW

**Comment by jmencak** [comment]
Thank you for the PR, Yanir.  This looks good to me, but I'd like `/lgtm` from PAO folk before I approve.

**Comment by cynepco3hahue** [comment]
PR looks straight forward to me
/lgtm

**Comment by cynepco3hahue** [comment]
@yanirq Looks like real problem
```
go install: github.com/onsi/ginkgo/ginkgo@v1.16.5: cannot query module due to -mod=vendor
Running Functional Tests: test/e2e/performanceprofile/functests
hack/run-functests.sh: line 31: ginkgo: command not found
make: *** [Makefile:167: pao-functests-only] Error 127
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-03-28T09:35:16Z"}
error: failed to execute wrapped command: exit status 2 
INFO[2022-03-28T09:35:26Z] Step e2e-gcp-pao-test failed after 20s.      
INFO[2022-03-28T09:35:26Z] Step phase test failed after 20s. 
```
Probably some env variables missed or you need to specify an absolute path to ginkgo.

**Comment by cynepco3hahue** [comment]
I am ok to fix it under the separate PR.

**Comment by jmencak** [comment]
> @yanirq Looks like real problem
> 
> ```
> go install: github.com/onsi/ginkgo/ginkgo@v1.16.5: cannot query module due to -mod=vendor
> Running Functional Tests: test/e2e/performanceprofile/functests
> hack/run-functests.sh: line 31: ginkgo: command not found
> make: *** [Makefile:167: pao-functests-only] Error 127
> {"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-03-28T09:35:16Z"}
> error: failed to execute wrapped command: exit status 2 
> INFO[2022-03-28T09:35:26Z] Step e2e-gcp-pao-test failed after 20s.      
> INFO[2022-03-28T09:35:26Z] Step phase test failed after 20s. 
> ```
> 
> Probably some env variables missed or you need to specify an absolute path to ginkgo.

I think the binary needs to be installed.  NTO doesn't use the binary.

**Pull request merged**
