### PR TITLE
NTO Metrics

### PR DESCRIPTION
**Pull request by jmencak**
Add basic support for Metrics and Alerts.

The following metrics are implemented:
  - nto_pod_labels_used_info
  - nto_profile_set_total
  - nto_build_info
  - nto_degraded_info

Two alerts (NTOPodsNotReady, NTODegraded) are currently being triggered when:
  - Pods are not ready in the Operator namespace for more than 30 minutes.
  - Operator itself is degraded for more than two hours.

### CODE REVIEW

**Comment by jmencak** [comment]
While this is marked WiP, this code is tested and I do not expect any major changes.  Please review @zvonkok 

/cc @courtneypacheco

**Comment by jmencak** [comment]
/hold
e2e tests need to be fixed not to combine stdout and stderr

**Comment by jmencak** [comment]
@courtneypacheco PTAL

**Comment by jmencak** [comment]
Had to rebase again due to merged PR177.

**Review by courtneypacheco — APPROVED** [review]
/lgtm

**Pull request merged**
