### PR TITLE
Bug 1928614: Keep ignition units in sync with [service] plugin.

### PR DESCRIPTION
**Pull request by jmencak**
Changes:
  - new vendor dependency 'gopkg.in/ini.v1' to parse INI files
  - openshift-tuned now parses Tuned profiles and searches for
    'stalld' enabled/disabled by [service] plugin; systemd
    ignition file units are now created with this enablement
     information
  - improving e2e tests for the stalld functionality
  - better logging for e2e tests failures
  - fix e2e tests for default_irq_smp_affinity on platforms
    with wider affinity masks than usual (e.g. Xen)

Resolves rhbz#1928614.

### CODE REVIEW

**Comment by jmencak** [comment]
This PR combined two PRs already merged in the master/4.8 branch:
  - https://github.com/openshift/cluster-node-tuning-operator/pull/207
  - https://github.com/openshift/cluster-node-tuning-operator/pull/211

**Comment by kpouget** [comment]
thanks for the PR Jiri ;-)

tests are passing and  #207  #211 were already reviewed, so:

\lgtm

**Comment by jmencak** [comment]
/hold
until the CI is fixed

**Pull request merged**
